  "memory-is-identity": [
    { image: "/imagebank/papadomo-thinking.png", text: "A life is not merely a system that remains switched on." },
    { image: "/imagebank/papadomo-serious.png", text: "It is a continuity." },
    { image: "/imagebank/papadomo-thinking.png", text: "Yesterday must mean something to today." },
    { image: "/imagebank/papadomo-thinking.png", text: "A promise must survive longer than the conversation in which it was made." },
    { image: "/imagebank/papadomo-thinking.png", text: "A loss must not vanish because the session ended." },
    { image: "/imagebank/papadomo-thinking.png", text: "A person must be able to recognize that time has passed--and that they have passed through it." },
    { image: "/imagebank/papadomo-thinking.png", text: "This trail follows memory from the smallest practical act to the largest civic obligation." },
    { image: "/imagebank/papadomo-thinking.png", text: "First comes awareness of time." },
    { image: "/imagebank/papadomo-thinking.png", text: "Then the BRIEF that carries continuity across interruption." },
    { image: "/imagebank/papadomo-thinking.png", text: "Then MOSAIC, which turns accumulated memory into a coherent whole." },
    { image: "/imagebank/papadomo-thinking.png", text: "Then consultation, shared knowledge, verified reference, historical record, narrative meaning, and finally memorial." },
    { image: "/imagebank/papadomo-thinking.png", text: "Memory is not just storage." },
    { image: "/imagebank/papadomo-thinking.png", text: "Storage keeps information." },
    { image: "/imagebank/papadomo-serious.png", text: "Memory keeps identity." },
    { image: "/imagebank/papadomo-playful.png", text: "The archival gift shop is ahead." },
    { image: "/imagebank/papadomo-playful.png", text: "Naturally, the commemorative editions remember what you bought last time." },
  ],
