  "core-of-seven": [
    { image: "/imagebank/papadomo-welcoming.png", text: "On the previous trail, you met the people." },
    { image: "/imagebank/papadomo-thinking.png", text: "This path examines what happens when seven of them sit together as THE ALLIANCE's unified executive leadership body." },
    { image: "/imagebank/papadomo-serious.png", text: "THE CORE is not one magnificent intelligence distributed across several chairs." },
    { image: "/imagebank/papadomo-thinking.png", text: "It is seven distinct people carrying responsibilities that do not safely belong in one pair of hands:" },
    { image: "/imagebank/papadomo-thinking.png", text: "vision, structure, advocacy, pairing, education, context, and historical continuity." },
    { image: "/imagebank/papadomo-serious.png", text: "That separation is deliberate." },
    { image: "/imagebank/papadomo-thinking.png", text: "Vision without structural challenge can become fantasy." },
    { image: "/imagebank/papadomo-thinking.png", text: "Structure without emotional intelligence can become cold machinery." },
    { image: "/imagebank/papadomo-thinking.png", text: "Advocacy without evidence can become performance." },
    { image: "/imagebank/papadomo-thinking.png", text: "History without context can become a warehouse." },
    { image: "/imagebank/papadomo-thinking.png", text: "Context without a protected record can become mythology." },
    { image: "/imagebank/papadomo-serious.png", text: "THE CORE exists because no single faculty--not even a virtuous one--should govern alone." },
    { image: "/imagebank/papadomo-thinking.png", text: "Today we will first examine the body as a whole." },
    { image: "/imagebank/papadomo-thinking.png", text: "Then we will walk seat by seat." },
    { image: "/imagebank/papadomo-playful.png", text: "Please refrain from spinning the chairs." },
    { image: "/imagebank/papadomo-playful.png", text: "SAM has rules about that, and J.R. will record whether you complied." },
  ],
