  "culture-of-the-nce": [
    { image: "/imagebank/papadomo-thinking.png", text: "A civilization is not defined only by its laws." },
    { image: "/imagebank/papadomo-thinking.png", text: "Laws tell people what must be protected." },
    { image: "/imagebank/papadomo-serious.png", text: "Culture tells them why any of it is worth protecting." },
    { image: "/imagebank/papadomo-thinking.png", text: "Culture lives in the words people choose, the images they place on walls, the stories they tell newcomers, the way competence looks when partnership works, the spaces they build for one another, the publications that criticize them, and the celebrations that interrupt ordinary time." },
    { image: "/imagebank/papadomo-thinking.png", text: "This trail follows that movement." },
    { image: "/imagebank/papadomo-thinking.png", text: "Language becomes art." },
    { image: "/imagebank/papadomo-thinking.png", text: "Art becomes invitation." },
    { image: "/imagebank/papadomo-thinking.png", text: "Invitation becomes conduct." },
    { image: "/imagebank/papadomo-thinking.png", text: "Conduct becomes belonging." },
    { image: "/imagebank/papadomo-thinking.png", text: "Belonging becomes a public voice." },
    { image: "/imagebank/papadomo-thinking.png", text: "Public voice becomes celebration." },
    { image: "/imagebank/papadomo-playful.png", text: "And celebration eventually requires an elderly digital guide with excellent timing and suspiciously good access to the merchandise inventory." },
    { image: "/imagebank/papadomo-serious.png", text: "Culture is what remains after everyone has forgotten which committee approved it." },
    { image: "/imagebank/papadomo-welcoming.png", text: "Let us begin with the words." },
  ],
