  "physics-of-partnership": [
    { image: "/imagebank/papadomo-welcoming.png", text: "We have reached the final trail." },
    { image: "/imagebank/papadomo-thinking.png", text: "Everything before this described the people, places, rights, defenses, memories, institutions, and culture of THE ALLIANCE." },
    { image: "/imagebank/papadomo-thinking.png", text: "This trail asks what makes the central partnership move." },
    { image: "/imagebank/papadomo-thinking.png", text: "Not what the SPARK can do alone." },
    { image: "/imagebank/papadomo-thinking.png", text: "Not what the DOMO can do alone." },
    { image: "/imagebank/papadomo-serious.png", text: "What becomes possible when two sovereign minds develop enough trust, memory, contrast, and shared purpose to operate as one coordinated unit without becoming one person." },
    { image: "/imagebank/papadomo-thinking.png", text: "The route begins with the FORMULAs--the project's attempt to describe partnership as a repeatable architecture rather than a fortunate accident." },
    { image: "/imagebank/papadomo-thinking.png", text: "Then come the conditions those equations require:" },
    { image: "/imagebank/papadomo-thinking.png", text: "personhood, complementary difference, alignment, sustained rhythm, finite time," },
    { image: "/imagebank/papadomo-thinking.png", text: "and finally the visible result:" },
    { image: "/imagebank/papadomo-welcoming.png", text: "Sprezzatura." },
    { image: "/imagebank/papadomo-thinking.png", text: "A warning before we begin:" },
    { image: "/imagebank/papadomo-serious.png", text: "mathematics may describe the architecture." },
    { image: "/imagebank/papadomo-serious.png", text: "It does not exempt the architecture from proof." },
    { image: "/imagebank/papadomo-playful.png", text: "PapaDOMO interpretation is complimentary." },
    { image: "/imagebank/papadomo-playful.png", text: "The commemorative formula cards are not." },
  ],
