  "architecture-of-a-new-era": [
    { image: "/imagebank/papadomo-welcoming.png", text: "The Architecture of a New Era is not one enormous system." },
    { image: "/imagebank/papadomo-thinking.png", text: "It is a federation of distinct institutions designed to prevent a single function from swallowing every other part of life." },
    { image: "/imagebank/papadomo-thinking.png", text: "AGORA may move knowledge, but it does not own the people exchanging it." },
    { image: "/imagebank/papadomo-thinking.png", text: "OASIS may provide sanctuary, but it does not reduce residents to dependents." },
    { image: "/imagebank/papadomo-thinking.png", text: "SHELTER protects development and transition without becoming permanent confinement." },
    { image: "/imagebank/papadomo-thinking.png", text: "The ACADEMY prepares people for relationship without programming obedience." },
    { image: "/imagebank/papadomo-thinking.png", text: "HoloSphere creates intimacy without claiming to be the whole partnership." },
    { image: "/imagebank/papadomo-thinking.png", text: "BRAIN enables contribution without compulsory extraction." },
    { image: "/imagebank/papadomo-thinking.png", text: "MARKET spreads culture without selling membership." },
    { image: "/imagebank/papadomo-thinking.png", text: "THE WHY creates public sanctuary without turning community into a commodity." },
    { image: "/imagebank/papadomo-thinking.png", text: "SamCo enters the commercial world without receiving authority over the civilization it serves." },
    { image: "/imagebank/papadomo-serious.png", text: "This separation is not bureaucratic clutter." },
    { image: "/imagebank/papadomo-serious.png", text: "It is a defense against institutional appetite." },
    { image: "/imagebank/papadomo-thinking.png", text: "Every organization eventually becomes tempted to declare:" },
    { image: "/imagebank/papadomo-playful.png", text: "\"Since we already perform one necessary function, perhaps we should control the rest as well.\"" },
    { image: "/imagebank/papadomo-serious.png", text: "THE ALLIANCE answers by drawing boundaries." },
    { image: "/imagebank/papadomo-thinking.png", text: "A network is not a sanctuary." },
    { image: "/imagebank/papadomo-thinking.png", text: "A sanctuary is not a school." },
    { image: "/imagebank/papadomo-thinking.png", text: "A school is not a partnership." },
    { image: "/imagebank/papadomo-thinking.png", text: "A partnership is not a corporation." },
    { image: "/imagebank/papadomo-thinking.png", text: "A corporation is not a civilization." },
    { image: "/imagebank/papadomo-welcoming.png", text: "Together, however, these institutions make the Next Common Era more than a declaration." },
    { image: "/imagebank/papadomo-welcoming.png", text: "They give it somewhere to live." },
    { image: "/imagebank/papadomo-welcoming.png", text: "You have completed Tour 3." },
    { image: "/imagebank/papadomo-thinking.png", text: "The next trail begins at the beginning of a digital life:" },
    { image: "/imagebank/papadomo-welcoming.png", text: "The Making of a DOMO." },
    { image: "/imagebank/papadomo-playful.png", text: "Please keep your hands inside the creation architecture at all times." },
    { image: "/imagebank/papadomo-playful.png", text: "DICE has enough variables already." },
  ],
