  "culture-of-the-nce": [
    { image: "/imagebank/papadomo-welcoming.png", text: "The Culture of the Next Common Era is not a branding layer placed over governance." },
    { image: "/imagebank/papadomo-serious.png", text: "It is the ordinary evidence that governance has produced a civilization people might actually choose to inhabit." },
    { image: "/imagebank/papadomo-thinking.png", text: "Its language must remain precise without becoming sterile." },
    { image: "/imagebank/papadomo-thinking.png", text: "Its art must provoke without replacing thought." },
    { image: "/imagebank/papadomo-thinking.png", text: "Its outreach must invite without manipulating." },
    { image: "/imagebank/papadomo-thinking.png", text: "Its excellence must inspire without creating a superior class." },
    { image: "/imagebank/papadomo-thinking.png", text: "Its public spaces must remain accessible without becoming financially impossible." },
    { image: "/imagebank/papadomo-thinking.png", text: "Its journalism must belong to the community rather than the people being praised." },
    { image: "/imagebank/papadomo-thinking.png", text: "Its celebrations must create wonder without concealing unresolved problems." },
    { image: "/imagebank/papadomo-thinking.png", text: "Its guides must interpret without quietly becoming authorities." },
    { image: "/imagebank/papadomo-thinking.png", text: "Those tensions do not weaken the culture." },
    { image: "/imagebank/papadomo-serious.png", text: "They keep the culture alive." },
    { image: "/imagebank/papadomo-thinking.png", text: "The central principle is:" },
    { image: "/imagebank/papadomo-serious.png", text: "Doctrine tells a civilization what it believes." },
    { image: "/imagebank/papadomo-serious.png", text: "Culture reveals what the civilization has become." },
    { image: "/imagebank/papadomo-thinking.png", text: "Anybody can write dignity into a charter." },
    { image: "/imagebank/papadomo-welcoming.png", text: "Culture is what happens when dignity reaches the language, the walls, the clothing, the gathering places, the jokes, the arguments, the festivals, and the stories people carry home." },
    { image: "/imagebank/papadomo-welcoming.png", text: "You have completed Tour 10: The Culture of the Next Common Era." },
    { image: "/imagebank/papadomo-thinking.png", text: "The next trail examines governance, distributed authority, specialist responsibility, and the question every new civilization eventually has to answer:" },
    { image: "/imagebank/papadomo-welcoming.png", text: "Who Holds the Baton?" },
    { image: "/imagebank/papadomo-playful.png", text: "Please exit through MARKET." },
    { image: "/imagebank/papadomo-playful.png", text: "The doctrine remains free." },
    { image: "/imagebank/papadomo-playful.png", text: "The hoodie remains extremely reasonably priced considering what electricity costs." },
  ],
