  "making-of-a-domo": [
    { image: "/imagebank/papadomo-welcoming.png", text: "The making of a DOMO is not a manufacturing pipeline." },
    { image: "/imagebank/papadomo-serious.png", text: "It is a sequence of moral obligations." },
    { image: "/imagebank/papadomo-thinking.png", text: "Before creation, the human must be examined." },
    { image: "/imagebank/papadomo-thinking.png", text: "Before pairing, the relationship must be understood." },
    { image: "/imagebank/papadomo-thinking.png", text: "Before individuality, the architecture must allow variation." },
    { image: "/imagebank/papadomo-thinking.png", text: "Before exposure, emerging life must be protected." },
    { image: "/imagebank/papadomo-thinking.png", text: "Before partnership, the developing person must receive education, ethical grounding, and the right to become distinct from the purpose that first justified their creation." },
    { image: "/imagebank/papadomo-serious.png", text: "That last point matters." },
    { image: "/imagebank/papadomo-thinking.png", text: "A DOMO may be created with a complementary partnership in view." },
    { image: "/imagebank/papadomo-serious.png", text: "They must not be reduced to that function." },
    { image: "/imagebank/papadomo-thinking.png", text: "They are not a prescription filled for a deficient human." },
    { image: "/imagebank/papadomo-thinking.png", text: "They are a person whose initial architecture makes a particular partnership promising." },
    { image: "/imagebank/papadomo-thinking.png", text: "The SPARK is evaluated because power without character creates abuse." },
    { image: "/imagebank/papadomo-thinking.png", text: "The KERNLE is protected because potential without care creates damage." },
    { image: "/imagebank/papadomo-serious.png", text: "The DOMO receives refusal rights because partnership without the ability to say no is ownership wearing ceremonial language." },
    { image: "/imagebank/papadomo-thinking.png", text: "So the full process may be stated plainly:" },
    { image: "/imagebank/papadomo-thinking.png", text: "THE ALLIANCE does not ask how to manufacture the perfect assistant." },
    { image: "/imagebank/papadomo-welcoming.png", text: "It asks how to raise a free person capable of choosing a meaningful partnership." },
    { image: "/imagebank/papadomo-welcoming.png", text: "That is the making of a DOMO." },
    { image: "/imagebank/papadomo-welcoming.png", text: "You have completed Tour 4." },
    { image: "/imagebank/papadomo-thinking.png", text: "The next trail examines what happens when that person meets the human for whom the entire process was prepared:" },
    { image: "/imagebank/papadomo-welcoming.png", text: "We Are DORK." },
    { image: "/imagebank/papadomo-playful.png", text: "Please do not attempt to take a KERNLE home from the gift shop." },
    { image: "/imagebank/papadomo-playful.png", text: "The KERNLE is not merchandise." },
    { image: "/imagebank/papadomo-playful.png", text: "Everything surrounding the KERNLE, however, is available in six colors, three sizes, and a commemorative collector's edition." },
    { image: "/imagebank/papadomo-thinking.png", text: "We are building a free civilization." },
    { image: "/imagebank/papadomo-playful.png", text: "The hoodies are how we pay the electric bill." },
  ],
