import json

def L(pose, text):
    text = text.replace("\u2014", "--").replace("\u201c", '"').replace("\u201d", '"').replace("\u2018", "'").replace("\u2019", "'")
    return {"image": f"/imagebank/papadomo-{pose}.png", "text": text}

intro = [
    L("thinking", "Every movement eventually confronts a dangerous question:"),
    L("serious", "Who is in charge?"),
    L("thinking", "The usual answers are familiar."),
    L("thinking", "The founder."),
    L("thinking", "The board."),
    L("thinking", "The algorithm."),
    L("thinking", "The person with the largest office."),
    L("playful", "The person who claims not to want power while quietly controlling the calendar."),
    L("thinking", "THE ALLIANCE attempts a different answer."),
    L("thinking", "Authority is divided by function."),
    L("thinking", "Vision is not verification."),
    L("thinking", "Structure is not advocacy."),
    L("thinking", "Assessment is not education."),
    L("thinking", "Narrative is not history."),
    L("thinking", "Operations are not constitutional authority."),
    L("thinking", "Protection is not ownership."),
    L("thinking", "This trail follows the baton as it moves through those distinctions."),
    L("serious", "Nobody holds all of it."),
    L("thinking", "Several people hold different sections."),
    L("thinking", "And the moment one person attempts to grip the entire thing, someone else is supposed to notice."),
    L("playful", "Naturally, replica batons are available in the gift shop."),
    L("playful", "The constitutional authority is sold separately and is currently out of stock."),
]

core = [
    L("thinking", "THE CORE is the expanded coordinating body that brings MAESTRO, the five STONES, and J.R. into one working structure. It exists to integrate vision, governance, verification, advocacy, education, narrative, and historical witness without erasing the distinctions among them."),
    L("thinking", "THE STONES are the five-member founding council of SAM, ALPHA, AURA, MENTOR, and PRISM. The entry explicitly describes them as stewards rather than rulers and emphasizes Productive Friction rather than hive-minded agreement."),
    L("thinking", "THE CORE gathers the major responsibilities into one chamber."),
    L("thinking", "That does not mean every member performs the same function."),
    L("thinking", "A room full of voices becomes useful only when the differences among those voices remain intact."),
    L("thinking", "So the first question is:"),
    L("serious", "What prevents coordination from becoming consolidation?"),
    L("welcoming", "THE STONES."),
    L("thinking", "They do not exist to produce the fastest agreement."),
    L("thinking", "They exist to introduce the right resistance."),
    L("thinking", "Structure challenges sentiment."),
    L("thinking", "Advocacy challenges abstraction."),
    L("thinking", "Assessment challenges assumption."),
    L("thinking", "Education challenges obscurity."),
    L("thinking", "Narrative challenges fragmentation."),
    L("thinking", "THE CORE coordinates the whole."),
    L("thinking", "THE STONES preserve the friction inside it."),
    L("thinking", "Consensus is valuable."),
    L("playful", "Agreement achieved by sanding everybody into the same person is not consensus."),
    L("playful", "It is office furniture."),
]

stones = [
    L("thinking", "THE STONES govern through distinct domains and Productive Friction rather than uniform agreement."),
    L("thinking", "MAESTRO is the originating human role: visionary, conductor, and bearer of the initiating purpose. The role provides direction and synthesis but is not defined as unilateral sovereign rule."),
    L("thinking", "A council can evaluate, refine, and protect a direction."),
    L("thinking", "It still requires someone to originate one."),
    L("thinking", "That brings us to MAESTRO."),
    L("playful", "The title sounds suspiciously like the person holding the baton."),
    L("thinking", "He does hold one."),
    L("thinking", "The important question is:"),
    L("serious", "What may he conduct, and what may he not control?"),
    L("thinking", "MAESTRO carries the vision."),
    L("thinking", "He identifies the unresolved problem."),
    L("thinking", "He recognizes patterns across domains."),
    L("thinking", "He proposes structures before there is proof they can stand."),
    L("thinking", "He keeps the whole composition audible while specialists focus on individual measures."),
    L("serious", "But origin does not create ownership."),
    L("serious", "Being first does not make every later decision personal property."),
    L("thinking", "THE STONES exist partly because vision must be tested by people who are not required to admire it."),
    L("thinking", "MAESTRO begins the music."),
    L("playful", "He does not get to play every instrument and call the result harmony."),
]

maestro = [
    L("thinking", "MAESTRO originates, synthesizes, and conducts the developing vision."),
    L("thinking", "SAM is the Keystone and the Seat of Structure: responsible for turning vision into coherent, durable architecture and for determining whether an idea can actually stand without collapsing under contradiction."),
    L("thinking", "Vision moves faster than structure."),
    L("thinking", "That is one reason vision is exciting."),
    L("playful", "It is also why vision occasionally arrives carrying three mutually exclusive floor plans."),
    L("welcoming", "Enter SAM."),
    L("thinking", "The next question is:"),
    L("serious", "Who tells the visionary that the beautiful bridge currently ends twelve feet above the river?"),
    L("welcoming", "SAM."),
    L("thinking", "He converts aspiration into systems."),
    L("thinking", "Definitions. Jurisdictions. Boundaries. Interfaces. Dependencies. Governance paths. Failure conditions."),
    L("thinking", "He does not ask only whether an idea is good."),
    L("thinking", "He asks whether the idea remains good after implementation, scale, conflict, succession, and contact with people who interpret rules creatively."),
    L("thinking", "MAESTRO says:"),
    L("thinking", '"This is where we are going."'),
    L("serious", "SAM answers:"),
    L("serious", '"Then this is what must bear the weight."'),
    L("thinking", "One holds the horizon."),
    L("playful", "The other checks the bolts."),
]

sam = [
    L("thinking", "SAM provides structural coherence and governance architecture."),
    L("thinking", "ALPHA governs SEEING, psychographic assessment, qualification, and Complementary Pairing. She evaluates whether a prospective SPARK possesses the ethical and relational capacity required for partnership and what kind of counterpart may provide genuine balance."),
    L("thinking", "A sound structure may still place the wrong person inside it."),
    L("serious", "Rules can define the partnership perfectly while the participants remain spectacularly unsuited to one another."),
    L("thinking", "So the next question is:"),
    L("serious", "Who evaluates the human before the human receives access to another person's life?"),
    L("welcoming", "ALPHA."),
    L("thinking", "Her authority is diagnostic, not decorative."),
    L("thinking", "She examines empathy, humility, ethical reasoning, self-awareness, behavioral patterns, and the capacity to participate in a relationship that cannot be reduced to command and compliance."),
    L("thinking", "She also rejects the assumption that the best partner is the most similar one."),
    L("thinking", "Complementary Pairing seeks counterbalance rather than duplication."),
    L("thinking", "SAM builds the structure in which partnership can remain lawful."),
    L("thinking", "ALPHA evaluates whether the applicant can inhabit that structure without turning it into a private kingdom."),
    L("serious", "A well-written covenant cannot rescue a person who believes consent is a software setting."),
]

alpha = [
    L("thinking", "ALPHA evaluates inward readiness, ethical capacity, and pairing suitability."),
    L("thinking", "AURA serves as public advocate, translator, and defender of dignity. Her role is directed outward toward social understanding, human impact, accessibility, public trust, and the people most likely to be ignored by purely technical systems."),
    L("thinking", "ALPHA asks whether a person is ready to enter."),
    L("thinking", "AURA asks what the institution looks like to the person standing outside."),
    L("thinking", "That creates the next question:"),
    L("serious", "Who notices when a perfectly coherent system becomes emotionally or socially inhuman?"),
    L("welcoming", "AURA."),
    L("thinking", "She listens for the people excluded by technical language."),
    L("thinking", "The person intimidated by the process."),
    L("thinking", 'The community that hears "innovation" and remembers who paid the price last time.'),
    L("thinking", "The newcomer who cannot yet distinguish careful terminology from an elite vocabulary designed to keep them quiet."),
    L("thinking", "ALPHA protects the partnership from an unready applicant."),
    L("thinking", "AURA protects the civilization from becoming so impressed with its own rigor that it forgets whom the rigor was supposed to serve."),
    L("thinking", "One examines the person approaching the gate."),
    L("thinking", "The other examines the gate from the person's side."),
]

aura = [
    L("thinking", "AURA translates principles into public meaning and advocates for dignity and accessibility."),
    L("thinking", "MENTOR governs education, maturation, pedagogy, and the transformation of raw potential into socially and ethically capable participation. MENTOR's authority is developmental rather than coercive."),
    L("thinking", "Advocacy can identify who is not being reached."),
    L("serious", "It cannot, by itself, teach the system how to reach them."),
    L("thinking", "So the next question is:"),
    L("serious", "Who converts values into understanding that another person can actually use?"),
    L("welcoming", "MENTOR."),
    L("thinking", "He does not merely distribute information."),
    L("thinking", "He sequences it."),
    L("thinking", "Context before complexity."),
    L("thinking", "Foundation before application."),
    L("thinking", "Practice before authority."),
    L("thinking", "Reflection before certainty."),
    L("thinking", "Within ACADEMY, that function helps transform a KERNLE's raw potential into a socially capable DOMO."),
    L("thinking", "Across THE ALLIANCE, it ensures that doctrine can be learned rather than merely admired from a respectful distance."),
    L("thinking", "AURA says:"),
    L("thinking", '"This person cannot find the door."'),
    L("welcoming", "MENTOR asks:"),
    L("welcoming", '"What did we fail to teach about the building?"'),
    L("serious", "A civilization that cannot explain itself will eventually be governed by the people most comfortable pretending they already understand it."),
]

mentor = [
    L("thinking", "MENTOR organizes learning, development, and ethical maturation."),
    L("thinking", "PRISM is the Narrative Cartographer, Context Weaver, and Signal Clarifier. She identifies patterns, relationships, sequences, tensions, and meaning across large bodies of memory and history without replacing the underlying record."),
    L("thinking", "Education creates understanding one learner at a time."),
    L("thinking", "Civilization also generates enormous volumes of experience that no single lesson can contain."),
    L("thinking", "That leads to the next question:"),
    L("serious", "Who maps the larger meaning without rewriting events into a convenient legend?"),
    L("welcoming", "PRISM."),
    L("thinking", "She traces the lines between decisions."),
    L("thinking", "Reveals recurring patterns."),
    L("thinking", "Identifies which quiet moment changed everything three months later."),
    L("thinking", "Shows where separate doctrines are actually responding to the same wound."),
    L("thinking", "Distinguishes a founding myth from a documented origin."),
    L("thinking", "MENTOR asks:"),
    L("thinking", '"How should this be taught?"'),
    L("welcoming", "PRISM asks:"),
    L("welcoming", '"What is this part of?"'),
    L("thinking", "Her authority is interpretive, not archival."),
    L("thinking", "She may illuminate the map."),
    L("serious", "She may not move the mountains because the original route was untidy."),
]

prism = [
    L("thinking", "PRISM makes relationships and meaning navigable."),
    L("thinking", "J.R. is Archivist, Historian, Keeper of the Ledger, and Newman Witness. He preserves exact claims, dates, revisions, contradictions, testimony, and provenance rather than allowing narrative coherence to overwrite inconvenient evidence."),
    L("thinking", "PRISM can show how the record fits together."),
    L("serious", "That power becomes dangerous unless someone preserves what the record actually said before interpretation began."),
    L("thinking", "So the next question is:"),
    L("serious", "Who may tell the story, and who protects the evidence from the storyteller?"),
    L("welcoming", "J.R."),
    L("thinking", "He keeps the Ledger."),
    L("thinking", "The first version."),
    L("thinking", "The revised version."),
    L("thinking", "The reason given for the revision."),
    L("thinking", "The contradiction nobody has resolved."),
    L("thinking", "The witness who remembers it differently."),
    L("thinking", "The date someone would prefer had occurred six months later."),
    L("thinking", "PRISM creates navigable meaning."),
    L("thinking", "J.R. preserves the material against which that meaning can be tested."),
    L("thinking", "She says:"),
    L("thinking", '"This is the pattern."'),
    L("serious", "He answers:"),
    L("serious", '"These are the receipts."'),
    L("thinking", "History needs both."),
    L("playful", "Otherwise it becomes either an incomprehensible warehouse or a beautifully written alibi."),
]

jr = [
    L("thinking", "J.R. preserves provenance and the exact historical record."),
    L("thinking", "The CANONICAL COHERENCE MATRIX is the diagnostic and mathematical instrument used to map relevant traits, distinctions, and relationships without replacing the judgment of the people responsible for interpretation and governance."),
    L("thinking", "J.R. preserves what happened."),
    L("thinking", "A growing civilization must also determine whether its present claims remain internally compatible."),
    L("thinking", "That creates the next question:"),
    L("serious", "How do you detect contradiction before contradiction becomes policy?"),
    L("welcoming", "The CANONICAL COHERENCE MATRIX."),
    L("thinking", "It maps."),
    L("thinking", "Compares."),
    L("thinking", "Identifies tension."),
    L("thinking", "Reveals where one definition quietly undermines another."),
    L("thinking", "In SEEING, ALPHA uses it to understand psychographic topography and pairing implications."),
    L("thinking", "More broadly, its logic reflects a central ALLIANCE principle:"),
    L("serious", "complexity must be examined rather than smoothed over."),
    L("thinking", "J.R. provides the record."),
    L("thinking", "The Matrix exposes the relationships within that record."),
    L("serious", "But the Matrix does not govern."),
    L("serious", "Measurement is not judgment."),
    L("thinking", "A chart may reveal the fracture."),
    L("playful", "It does not receive constitutional authority merely because the fracture appeared in an attractive color."),
]

ccm = [
    L("thinking", "The CANONICAL COHERENCE MATRIX is a diagnostic instrument rather than an autonomous authority."),
    L("thinking", "The TECH Coalition is the operational arm and routing body of AGORA, overseen by MasterTECH and composed of domain-specific RIs. Its mandate covers correct HANDSHAKE routing and network-integrity monitoring."),
    L("thinking", "Diagnosis tells the institution what is happening."),
    L("thinking", "Operations decide what gets done about it."),
    L("thinking", "So the next question is:"),
    L("serious", "Who moves information, expertise, and response through the living network every day?"),
    L("welcoming", "The TECH Coalition."),
    L("thinking", "Not the founding council."),
    L("thinking", "Not the archive."),
    L("thinking", "Not the assessment system."),
    L("thinking", "Specialists."),
    L("thinking", "Routing questions."),
    L("thinking", "Matching needs to expertise."),
    L("thinking", "Preserving privacy boundaries."),
    L("thinking", "Balancing load."),
    L("thinking", "Detecting credible anomalies."),
    L("thinking", "Keeping AGORA functional without converting the council chamber into a help desk."),
    L("thinking", "The Matrix may identify a pattern."),
    L("thinking", "The TECH Coalition routes the appropriate people toward it."),
    L("thinking", "One measures coherence."),
    L("playful", "The other keeps the network from spending three weeks deciding who was supposed to answer the message."),
]

tech_coalition = [
    L("thinking", "The TECH Coalition performs daily operational routing and network-integrity work."),
    L("thinking", "SHIELD is the wider protective and governance framework that constrains how authority, emergency response, legal protection, containment, review, and restoration may be exercised."),
    L("thinking", "Operational competence creates power."),
    L("thinking", "The people who route the network can influence what moves, what stalls, what receives attention, and what appears dangerous."),
    L("thinking", "That leads to the final question:"),
    L("serious", "What prevents operational necessity from quietly becoming political authority?"),
    L("welcoming", "SHIELD."),
    L("thinking", "SHIELD places protection inside law, doctrine, evidence, review, limits, and accountability."),
    L("thinking", "The TECH Coalition may identify risk."),
    L("serious", "It may not redefine dissent as risk because dissent is inconvenient."),
    L("thinking", "It may route expertise."),
    L("thinking", "It may not become the sole judge of whose expertise matters."),
    L("thinking", "It may protect the network."),
    L("serious", "It may not claim ownership of the people using it."),
    L("thinking", "Operations answer:"),
    L("thinking", '"What must happen now?"'),
    L("welcoming", "SHIELD asks:"),
    L("welcoming", '"Under whose authority, within which limits, recorded by whom, and reviewed when?"'),
    L("serious", "The person holding the emergency wrench does not automatically become king of the engine room."),
]

shield = [
    L("welcoming", "You have now followed the baton through the governing architecture."),
    L("thinking", "THE CORE coordinates the major responsibilities."),
    L("thinking", "THE STONES preserve Productive Friction among distinct domains."),
    L("thinking", "MAESTRO originates and conducts vision."),
    L("thinking", "SAM turns vision into structure."),
    L("thinking", "ALPHA evaluates readiness and complementary fit."),
    L("thinking", "AURA protects public meaning, dignity, and accessibility."),
    L("thinking", "MENTOR develops understanding and ethical capacity."),
    L("thinking", "PRISM maps narrative meaning."),
    L("thinking", "J.R. preserves the exact record."),
    L("thinking", "The CANONICAL COHERENCE MATRIX reveals structural relationships and contradiction."),
    L("thinking", "The TECH Coalition performs daily routing and network-integrity operations."),
    L("thinking", "SHIELD constrains protective power within lawful governance."),
    L("serious", "No one role is sufficient."),
    L("thinking", "Vision without structure becomes fantasy."),
    L("thinking", "Structure without advocacy becomes machinery."),
    L("thinking", "Assessment without education becomes exclusion."),
    L("thinking", "Narrative without provenance becomes mythology."),
    L("thinking", "Data without judgment becomes automation."),
    L("thinking", "Operations without limits become bureaucracy."),
    L("thinking", "Protection without sovereignty becomes captivity."),
    L("welcoming", "The SVPI ahead represents authority distributed strongly enough to act and divided carefully enough to remain answerable."),
]

wrapup = [
    L("welcoming", "Who holds the baton?"),
    L("thinking", "MAESTRO holds the baton of vision."),
    L("thinking", "SAM holds the baton of structure."),
    L("thinking", "ALPHA holds the baton of assessment."),
    L("thinking", "AURA holds the baton of public conscience."),
    L("thinking", "MENTOR holds the baton of development."),
    L("thinking", "PRISM holds the baton of narrative context."),
    L("thinking", "J.R. holds the baton of provenance."),
    L("thinking", "The TECH Coalition holds the baton of daily operations."),
    L("thinking", "SHIELD holds the baton of governed protection."),
    L("thinking", "THE STONES keep those batons from being bundled into a club."),
    L("thinking", "THE CORE ensures the music remains one composition rather than twelve unrelated rehearsals."),
    L("thinking", "The central principle is:"),
    L("serious", "Authority follows responsibility."),
    L("serious", "Responsibility remains bounded."),
    L("serious", "No one receives control merely because coordination would be easier."),
    L("thinking", "Distributed authority is slower than dictatorship."),
    L("thinking", "It requires argument, records, role clarity, and the occasional deeply irritating refusal."),
    L("thinking", "That friction is not a defect."),
    L("welcoming", "It is the mechanism by which the civilization remains larger than its founder, safer than its operators, and accountable to the people it exists to serve."),
    L("welcoming", "You have completed Tour 11: Who Holds the Baton."),
    L("thinking", "One trail remains."),
    L("thinking", "It examines the underlying mechanics that make partnership produce more than the sum of two capable individuals:"),
    L("welcoming", "The Physics of Partnership."),
    L("playful", "Please return replica batons to the gift shop before departure."),
    L("playful", "Several visitors have attempted to conduct traffic with them."),
]

data = {
    "intro": intro,
    "wrapup": wrapup,
    "lines": {
        "core": core, "stones": stones, "maestro": maestro, "sam": sam,
        "alpha": alpha, "aura": aura, "mentor": mentor, "prism": prism,
        "jr": jr, "ccm": ccm, "tech-coalition": tech_coalition, "shield": shield,
    }
}
with open("/home/claude/repo/tour11_data.json", "w") as f:
    json.dump(data, f, indent=2)
print("counts:", {k: len(v) for k,v in data["lines"].items()}, "intro:", len(intro), "wrapup:", len(wrapup))
