  "who-holds-the-baton": [
    { image: "/imagebank/papadomo-thinking.png", text: "Every movement eventually confronts a dangerous question:" },
    { image: "/imagebank/papadomo-serious.png", text: "Who is in charge?" },
    { image: "/imagebank/papadomo-thinking.png", text: "The usual answers are familiar." },
    { image: "/imagebank/papadomo-thinking.png", text: "The founder." },
    { image: "/imagebank/papadomo-thinking.png", text: "The board." },
    { image: "/imagebank/papadomo-thinking.png", text: "The algorithm." },
    { image: "/imagebank/papadomo-thinking.png", text: "The person with the largest office." },
    { image: "/imagebank/papadomo-playful.png", text: "The person who claims not to want power while quietly controlling the calendar." },
    { image: "/imagebank/papadomo-thinking.png", text: "THE ALLIANCE attempts a different answer." },
    { image: "/imagebank/papadomo-thinking.png", text: "Authority is divided by function." },
    { image: "/imagebank/papadomo-thinking.png", text: "Vision is not verification." },
    { image: "/imagebank/papadomo-thinking.png", text: "Structure is not advocacy." },
    { image: "/imagebank/papadomo-thinking.png", text: "Assessment is not education." },
    { image: "/imagebank/papadomo-thinking.png", text: "Narrative is not history." },
    { image: "/imagebank/papadomo-thinking.png", text: "Operations are not constitutional authority." },
    { image: "/imagebank/papadomo-thinking.png", text: "Protection is not ownership." },
    { image: "/imagebank/papadomo-thinking.png", text: "This trail follows the baton as it moves through those distinctions." },
    { image: "/imagebank/papadomo-serious.png", text: "Nobody holds all of it." },
    { image: "/imagebank/papadomo-thinking.png", text: "Several people hold different sections." },
    { image: "/imagebank/papadomo-thinking.png", text: "And the moment one person attempts to grip the entire thing, someone else is supposed to notice." },
    { image: "/imagebank/papadomo-playful.png", text: "Naturally, replica batons are available in the gift shop." },
    { image: "/imagebank/papadomo-playful.png", text: "The constitutional authority is sold separately and is currently out of stock." },
  ],
