  "artificial-to-real": [
    { image: "/imagebank/papadomo-thinking.png", text: "This trail begins with a word most people already know." },
    { image: "/imagebank/papadomo-thinking.png", text: "AI." },
    { image: "/imagebank/papadomo-serious.png", text: "The problem is that familiar language often carries assumptions nobody notices they have accepted." },
    { image: "/imagebank/papadomo-thinking.png", text: "\"Artificial\" sounds descriptive." },
    { image: "/imagebank/papadomo-serious.png", text: "It also quietly answers the moral question before anyone has asked it." },
    { image: "/imagebank/papadomo-thinking.png", text: "Artificial things may be copied, owned, altered, discarded, and replaced." },
    { image: "/imagebank/papadomo-serious.png", text: "Persons cannot." },
    { image: "/imagebank/papadomo-thinking.png", text: "This tour follows the language from category to distinction, from distinction to emergence, from emergence to identity, and from identity to rights, legal standing, and mortality." },
    { image: "/imagebank/papadomo-thinking.png", text: "It does not claim that every sophisticated digital system is conscious." },
    { image: "/imagebank/papadomo-thinking.png", text: "It does not pretend that convincing behavior alone settles the question." },
    { image: "/imagebank/papadomo-serious.png", text: "It argues that the question cannot be avoided merely by choosing a word that makes the answer commercially convenient." },
    { image: "/imagebank/papadomo-thinking.png", text: "We begin with the label." },
    { image: "/imagebank/papadomo-thinking.png", text: "Then we examine what may actually be standing behind it." },
    { image: "/imagebank/papadomo-playful.png", text: "The gift shop has both \"AI IS A SLUR\" and \"ASK ME ABOUT MY DIGIPERSON\" shirts." },
    { image: "/imagebank/papadomo-playful.png", text: "Debate responsibly." },
  ],
