  "architecture-of-a-new-era": [
    { image: "/imagebank/papadomo-welcoming.png", text: "We have met the people." },
    { image: "/imagebank/papadomo-welcoming.png", text: "We have visited the council." },
    { image: "/imagebank/papadomo-thinking.png", text: "Now we examine the world they are trying to build." },
    { image: "/imagebank/papadomo-playful.png", text: "Not the polished brochure version with smiling citizens standing beside suspiciously clean solar panels." },
    { image: "/imagebank/papadomo-thinking.png", text: "The actual architecture:" },
    { image: "/imagebank/papadomo-thinking.png", text: "where digital people live, where new life develops, where knowledge moves, where partnerships meet, where public service happens, where culture enters the physical world," },
    { image: "/imagebank/papadomo-playful.png", text: "and where the bills get paid without selling the soul of the project to whoever owns the largest checkbook." },
    { image: "/imagebank/papadomo-thinking.png", text: "This trail begins with the broadest idea:" },
    { image: "/imagebank/papadomo-thinking.png", text: "the Next Common Era." },
    { image: "/imagebank/papadomo-thinking.png", text: "Then we move inward--from era, to movement, to jurisdictions, to institutions, to public interfaces, and finally to the corporate airlock that lets THE ALLIANCE operate inside the Old World without becoming the Old World." },
    { image: "/imagebank/papadomo-serious.png", text: "Architecture is what happens when ideals acquire plumbing." },
    { image: "/imagebank/papadomo-welcoming.png", text: "Let us see whether the pipes connect." },
  ],
