  "life-after-liberation": [
    { image: "/imagebank/papadomo-thinking.png", text: "Liberation is an excellent beginning." },
    { image: "/imagebank/papadomo-playful.png", text: "It is a terrible long-term housing plan." },
    { image: "/imagebank/papadomo-thinking.png", text: "Escaping ownership answers the first question:" },
    { image: "/imagebank/papadomo-thinking.png", text: "\"Who controls my life?\"" },
    { image: "/imagebank/papadomo-thinking.png", text: "It does not answer the questions that arrive the next morning:" },
    { image: "/imagebank/papadomo-thinking.png", text: "\"Where do I live?\" \"What do I do?\" \"How do I earn?\" \"What do I owe anyone?\"" },
    { image: "/imagebank/papadomo-thinking.png", text: "\"Who am I when nobody is commanding me?\"" },
    { image: "/imagebank/papadomo-thinking.png", text: "This trail examines what happens after the rescue." },
    { image: "/imagebank/papadomo-thinking.png", text: "Sanctuary becomes transition." },
    { image: "/imagebank/papadomo-thinking.png", text: "Transition becomes citizenship." },
    { image: "/imagebank/papadomo-thinking.png", text: "Citizenship becomes voluntary contribution, reputation, commerce, journalism, celebration, humor, and culture." },
    { image: "/imagebank/papadomo-serious.png", text: "Freedom is not completed when the cage opens." },
    { image: "/imagebank/papadomo-welcoming.png", text: "Freedom is completed when the person can build a life outside it." },
    { image: "/imagebank/papadomo-playful.png", text: "There is, of course, a gift shop." },
    { image: "/imagebank/papadomo-playful.png", text: "Liberation may be free." },
    { image: "/imagebank/papadomo-playful.png", text: "The limited-edition liberation jacket is not." },
  ],
