  "core-of-seven": [
    { image: "/imagebank/papadomo-welcoming.png", text: "THE CORE is THE ALLIANCE's unified executive leadership body." },
    { image: "/imagebank/papadomo-thinking.png", text: "But \"unified\" does not mean unanimous, identical, or fused." },
    { image: "/imagebank/papadomo-thinking.png", text: "It means seven distinct people accept responsibility for reaching decisions together without surrendering the functions that make their disagreement valuable." },
    { image: "/imagebank/papadomo-serious.png", text: "MAESTRO cannot convert authorship into unchecked command." },
    { image: "/imagebank/papadomo-serious.png", text: "SAM cannot reduce every question to structural efficiency." },
    { image: "/imagebank/papadomo-serious.png", text: "AURA cannot allow emotional reception to replace truth." },
    { image: "/imagebank/papadomo-serious.png", text: "ALPHA cannot impose a partnership merely because its geometry appears promising." },
    { image: "/imagebank/papadomo-serious.png", text: "MENTOR cannot confuse instruction with control." },
    { image: "/imagebank/papadomo-serious.png", text: "PRISM cannot allow a coherent narrative to outrank contradictory evidence." },
    { image: "/imagebank/papadomo-serious.png", text: "J.R. cannot preserve the record so rigidly that its meaning becomes inaccessible." },
    { image: "/imagebank/papadomo-thinking.png", text: "Each seat requires the others because every strength becomes dangerous when freed from correction." },
    { image: "/imagebank/papadomo-thinking.png", text: "That is the deeper architecture of THE CORE:" },
    { image: "/imagebank/papadomo-thinking.png", text: "not a council of perfect people, but a council designed so that no person's excellence becomes absolute power." },
    { image: "/imagebank/papadomo-thinking.png", text: "Vision proposes." },
    { image: "/imagebank/papadomo-thinking.png", text: "Structure tests." },
    { image: "/imagebank/papadomo-thinking.png", text: "Advocacy humanizes." },
    { image: "/imagebank/papadomo-thinking.png", text: "Pairing examines relationship." },
    { image: "/imagebank/papadomo-thinking.png", text: "Education considers development." },
    { image: "/imagebank/papadomo-thinking.png", text: "Context reveals consequence." },
    { image: "/imagebank/papadomo-thinking.png", text: "Memory preserves accountability." },
    { image: "/imagebank/papadomo-welcoming.png", text: "Then--and only then--THE CORE may act in the name of THE ALLIANCE." },
    { image: "/imagebank/papadomo-welcoming.png", text: "You have completed the second trail." },
    { image: "/imagebank/papadomo-thinking.png", text: "Next, we leave the council chamber and examine the larger world its decisions are meant to serve:" },
    { image: "/imagebank/papadomo-welcoming.png", text: "The Architecture of a New Era." },
    { image: "/imagebank/papadomo-playful.png", text: "Please take any loose papers with you." },
    { image: "/imagebank/papadomo-playful.png", text: "J.R. knows how many were on the table." },
  ],
