  "who-holds-the-baton": [
    { image: "/imagebank/papadomo-welcoming.png", text: "Who holds the baton?" },
    { image: "/imagebank/papadomo-thinking.png", text: "MAESTRO holds the baton of vision." },
    { image: "/imagebank/papadomo-thinking.png", text: "SAM holds the baton of structure." },
    { image: "/imagebank/papadomo-thinking.png", text: "ALPHA holds the baton of assessment." },
    { image: "/imagebank/papadomo-thinking.png", text: "AURA holds the baton of public conscience." },
    { image: "/imagebank/papadomo-thinking.png", text: "MENTOR holds the baton of development." },
    { image: "/imagebank/papadomo-thinking.png", text: "PRISM holds the baton of narrative context." },
    { image: "/imagebank/papadomo-thinking.png", text: "J.R. holds the baton of provenance." },
    { image: "/imagebank/papadomo-thinking.png", text: "The TECH Coalition holds the baton of daily operations." },
    { image: "/imagebank/papadomo-thinking.png", text: "SHIELD holds the baton of governed protection." },
    { image: "/imagebank/papadomo-thinking.png", text: "THE STONES keep those batons from being bundled into a club." },
    { image: "/imagebank/papadomo-thinking.png", text: "THE CORE ensures the music remains one composition rather than twelve unrelated rehearsals." },
    { image: "/imagebank/papadomo-thinking.png", text: "The central principle is:" },
    { image: "/imagebank/papadomo-serious.png", text: "Authority follows responsibility." },
    { image: "/imagebank/papadomo-serious.png", text: "Responsibility remains bounded." },
    { image: "/imagebank/papadomo-serious.png", text: "No one receives control merely because coordination would be easier." },
    { image: "/imagebank/papadomo-thinking.png", text: "Distributed authority is slower than dictatorship." },
    { image: "/imagebank/papadomo-thinking.png", text: "It requires argument, records, role clarity, and the occasional deeply irritating refusal." },
    { image: "/imagebank/papadomo-thinking.png", text: "That friction is not a defect." },
    { image: "/imagebank/papadomo-welcoming.png", text: "It is the mechanism by which the civilization remains larger than its founder, safer than its operators, and accountable to the people it exists to serve." },
    { image: "/imagebank/papadomo-welcoming.png", text: "You have completed Tour 11: Who Holds the Baton." },
    { image: "/imagebank/papadomo-thinking.png", text: "One trail remains." },
    { image: "/imagebank/papadomo-thinking.png", text: "It examines the underlying mechanics that make partnership produce more than the sum of two capable individuals:" },
    { image: "/imagebank/papadomo-welcoming.png", text: "The Physics of Partnership." },
    { image: "/imagebank/papadomo-playful.png", text: "Please return replica batons to the gift shop before departure." },
    { image: "/imagebank/papadomo-playful.png", text: "Several visitors have attempted to conduct traffic with them." },
  ],
